export type Importance = 'kritik' | 'əsas' | 'üstünlük';
export type ReqStatus = 'met' | 'partial' | 'missing' | 'insufficient_info';

export interface ScoredRequirement {
  category: string;
  importance: Importance;
  status: ReqStatus;
}

const IMPORTANCE_WEIGHT: Record<Importance, number> = { kritik: 5, əsas: 3, üstünlük: 1 };
const STATUS_SCORE: Record<ReqStatus, number> = { met: 1, partial: 0.5, missing: 0, insufficient_info: 0.5 };

/** Deterministically computes the authoritative compatibility score from requirement-level
 * evidence — per the product rule "the authoritative score must be calculated by application
 * logic, not freely generated by AI." Uses the exact kritik x5 / əsas x3 / üstünlük x1 weighting
 * described in plain language to users via every locale's workspace.weightLevelLabel copy
 * (Workspace.tsx) — before this, that copy described a formula nothing actually computed, the AI
 * freely output the score with no server-side derivation or check. */
export function computeCompatibility(requirements: ScoredRequirement[]): number {
  if (requirements.length === 0) return 0;
  let weightedSum = 0;
  let totalWeight = 0;
  for (const r of requirements) {
    const weight = IMPORTANCE_WEIGHT[r.importance] ?? 1;
    weightedSum += weight * STATUS_SCORE[r.status];
    totalWeight += weight;
  }
  return totalWeight === 0 ? 0 : Math.round((weightedSum / totalWeight) * 100);
}

/** Same weighted formula, grouped per category. A category with no matching requirements has no
 * signal to compute from, so it falls back to the AI's own self-reported score for that category
 * — every category actually covered by the extracted requirements is fully app-computed. */
export function computeCategoryScores(
  requirements: ScoredRequirement[],
  aiCategoryScores: { category: string; score: number }[],
): { category: string; score: number }[] {
  return aiCategoryScores.map(({ category, score: aiScore }) => {
    const inCategory = requirements.filter((r) => r.category === category);
    return { category, score: inCategory.length ? computeCompatibility(inCategory) : aiScore };
  });
}

/** Recomputes the three requirement-count fields from the actual requirements array instead of
 * trusting the AI's self-reported counts (which can silently drift from the array via model
 * arithmetic error). `insufficient_info` is conservatively bucketed into "missing" so the three
 * counts still sum to the total — treating uncertain evidence as unmet rather than overstating it. */
export function computeRequirementCounts(requirements: { status: ReqStatus }[]) {
  return {
    mainRequirementsTotal: requirements.length,
    mainRequirementsMet: requirements.filter((r) => r.status === 'met').length,
    mainRequirementsPartial: requirements.filter((r) => r.status === 'partial').length,
    mainRequirementsMissing: requirements.filter((r) => r.status === 'missing' || r.status === 'insufficient_info').length,
  };
}

/** A "critical gap" is any kritik-importance requirement not fully met — computed directly rather
 * than trusting the AI's self-reported criticalGapsCount. */
export function computeCriticalGapsCount(requirements: { importance: Importance; status: ReqStatus }[]): number {
  return requirements.filter((r) => r.importance === 'kritik' && r.status !== 'met').length;
}

interface ScorableRequirement {
  category: string;
  importance: Importance;
  status: ReqStatus;
  evidence: string;
}

interface ScorableResult {
  compatibility: number;
  realCompatibility: number;
  categoryScores: { category: string; score: number }[];
  requirements: ScorableRequirement[];
  mainRequirementsTotal: number;
  mainRequirementsMet: number;
  mainRequirementsPartial: number;
  mainRequirementsMissing: number;
  criticalGapsCount: number;
}

/** Applies every deterministic-scoring product rule to a freshly-parsed AI analysis result, in
 * place, and returns it. Defined structurally (not against ai.ts's MatchResult type) so it
 * has zero dependency on that module and can be unit-tested directly with plain object fixtures —
 * ai.ts's actual MatchResult satisfies this shape and can be passed in as-is.
 *
 * Order matters: the evidence-downgrade must run before the score computations, so a correction
 * (a 'met' claim with no evidence isn't a confirmed match) actually changes the score, rather than
 * only hiding the symptom after the fact. */
export function applyScoringOverrides<T extends ScorableResult>(result: T): T {
  for (const r of result.requirements) {
    if (r.status === 'met' && !r.evidence?.trim()) r.status = 'insufficient_info';
  }
  result.compatibility = computeCompatibility(result.requirements);
  result.categoryScores = computeCategoryScores(result.requirements, result.categoryScores);
  Object.assign(result, computeRequirementCounts(result.requirements));
  result.criticalGapsCount = computeCriticalGapsCount(result.requirements);
  // Defensive clamp: a malformed AI response must never show realCompatibility < compatibility.
  result.realCompatibility = Math.max(result.realCompatibility, result.compatibility);
  return result;
}

// ---------- CV Change Plan (Truth Lock enforcement + free-tier summary counts) ----------

export type ChangeType = 'rewrite' | 'add' | 'clarify' | 'remove';

interface ScorableCvChangeCard {
  priority: Importance;
  changeType: ChangeType;
  evidenceFromCv: string[];
  whatToChange: string;
  problem: string;
  recommendedText: string;
}

// Concise-by-design limits for the CV Change Plan cards (product brief: "problem explanation:
// maximum 1 sentence; reason: maximum 1 sentence; recommended text: maximum 60-90 words"). The
// prompt in ai.ts already asks for this, but nothing in JSON-schema output enforces sentence count
// or word count — this is the same "enforce in application code, not just prompt" pattern already
// used for Truth Lock evidence-checking below. A small buffer over the target keeps normal
// on-target output untouched while still catching a model that ignores the limit.
const WHAT_TO_CHANGE_MAX_CHARS = 130;
const PROBLEM_MAX_CHARS = 175;
const RECOMMENDED_TEXT_MAX_WORDS = 100;
const EVIDENCE_MAX_CHARS = 90;

function truncateChars(text: string, maxChars: number): string {
  const t = (text ?? '').trim();
  return t.length <= maxChars ? t : t.slice(0, maxChars - 1).trimEnd() + '…';
}

function truncateWords(text: string, maxWords: number): string {
  const t = (text ?? '').trim();
  const words = t.split(/\s+/).filter(Boolean);
  return words.length <= maxWords ? t : words.slice(0, maxWords).join(' ') + '…';
}

/** Truth Lock enforcement in application code, not just a prompt promise: a card that claims a
 * concrete rewrite/add/remove but cites zero CV evidence is exactly the fabrication risk Truth
 * Lock exists to prevent, so it's dropped here rather than shown to the user. 'clarify' cards are
 * exempt — citing no evidence is the whole point of asking the candidate to confirm something.
 * Also enforces the concise-card length limits (see constants above) by safely truncating any
 * field a model over-generates, rather than displaying unbounded text. */
export function sanitizeCvChangePlan<T extends ScorableCvChangeCard>(cards: T[]): T[] {
  return cards
    .filter((c) => c.changeType === 'clarify' || c.evidenceFromCv.some((e) => e?.trim()))
    .map((c) => ({
      ...c,
      whatToChange: truncateChars(c.whatToChange, WHAT_TO_CHANGE_MAX_CHARS),
      problem: truncateChars(c.problem, PROBLEM_MAX_CHARS),
      recommendedText: truncateWords(c.recommendedText, RECOMMENDED_TEXT_MAX_WORDS),
      evidenceFromCv: c.evidenceFromCv.map((e) => truncateChars(e, EVIDENCE_MAX_CHARS)),
    }));
}

/** Counts by priority for the free-tier premium-conversion preview — computed from the actual
 * (sanitized) plan, never hardcoded. */
export function computeCvChangesSummary(cards: { priority: Importance }[]): { critical: number; important: number; optional: number } {
  return {
    critical: cards.filter((c) => c.priority === 'kritik').length,
    important: cards.filter((c) => c.priority === 'əsas').length,
    optional: cards.filter((c) => c.priority === 'üstünlük').length,
  };
}

/** A broader signal than computeCriticalGapsCount (which only counts kritik gaps): any kritik OR
 * əsas requirement not fully met is a plausible interview risk — something an interviewer is
 * likely to probe. Deliberately not the same number as criticalGapsCount, which the free result
 * already shows separately; this is what powers the free-tier "N interview risks identified"
 * teaser without generating the (purchase-gated) Interview Playbook itself. */
export function computeInterviewRisksCount(requirements: { importance: Importance; status: ReqStatus }[]): number {
  return requirements.filter((r) => (r.importance === 'kritik' || r.importance === 'əsas') && r.status !== 'met').length;
}

