export type Importance = 'kritik' | 'əsas' | 'üstünlük';
export type ReqStatus = 'met' | 'partial' | 'missing' | 'insufficient_info';

export interface ScoredRequirement {
  category: string;
  importance: Importance;
  status: ReqStatus;
}

const IMPORTANCE_WEIGHT: Record<Importance, number> = { kritik: 5, əsas: 3, üstünlük: 1 };
const STATUS_SCORE: Record<ReqStatus, number> = { met: 1, partial: 0.5, missing: 0, insufficient_info: 0.5 };

/** Deterministically computes the authoritative compatibility score from requirement-level
 * evidence — per the product rule "the authoritative score must be calculated by application
 * logic, not freely generated by AI." Uses the exact kritik x5 / əsas x3 / üstünlük x1 weighting
 * already promised to users via every locale's workspace.weightMultipliers copy (Workspace.tsx);
 * before this, that copy described a formula nothing actually computed — the AI freely output the
 * score with no server-side derivation or check. */
export function computeCompatibility(requirements: ScoredRequirement[]): number {
  if (requirements.length === 0) return 0;
  let weightedSum = 0;
  let totalWeight = 0;
  for (const r of requirements) {
    const weight = IMPORTANCE_WEIGHT[r.importance] ?? 1;
    weightedSum += weight * STATUS_SCORE[r.status];
    totalWeight += weight;
  }
  return totalWeight === 0 ? 0 : Math.round((weightedSum / totalWeight) * 100);
}

/** Same weighted formula, grouped per category. A category with no matching requirements has no
 * signal to compute from, so it falls back to the AI's own self-reported score for that category
 * — every category actually covered by the extracted requirements is fully app-computed. */
export function computeCategoryScores(
  requirements: ScoredRequirement[],
  aiCategoryScores: { category: string; score: number }[],
): { category: string; score: number }[] {
  return aiCategoryScores.map(({ category, score: aiScore }) => {
    const inCategory = requirements.filter((r) => r.category === category);
    return { category, score: inCategory.length ? computeCompatibility(inCategory) : aiScore };
  });
}

/** Recomputes the three requirement-count fields from the actual requirements array instead of
 * trusting the AI's self-reported counts (which can silently drift from the array via model
 * arithmetic error). `insufficient_info` is conservatively bucketed into "missing" so the three
 * counts still sum to the total — treating uncertain evidence as unmet rather than overstating it. */
export function computeRequirementCounts(requirements: { status: ReqStatus }[]) {
  return {
    mainRequirementsTotal: requirements.length,
    mainRequirementsMet: requirements.filter((r) => r.status === 'met').length,
    mainRequirementsPartial: requirements.filter((r) => r.status === 'partial').length,
    mainRequirementsMissing: requirements.filter((r) => r.status === 'missing' || r.status === 'insufficient_info').length,
  };
}

/** A "critical gap" is any kritik-importance requirement not fully met — computed directly rather
 * than trusting the AI's self-reported criticalGapsCount. */
export function computeCriticalGapsCount(requirements: { importance: Importance; status: ReqStatus }[]): number {
  return requirements.filter((r) => r.importance === 'kritik' && r.status !== 'met').length;
}

interface ScorableRequirement {
  category: string;
  importance: Importance;
  status: ReqStatus;
  evidence: string;
}

interface ScorableResult {
  compatibility: number;
  realCompatibility: number;
  categoryScores: { category: string; score: number }[];
  requirements: ScorableRequirement[];
  mainRequirementsTotal: number;
  mainRequirementsMet: number;
  mainRequirementsPartial: number;
  mainRequirementsMissing: number;
  criticalGapsCount: number;
}

/** Applies every deterministic-scoring product rule to a freshly-parsed AI analysis result, in
 * place, and returns it. Defined structurally (not against anthropic.ts's MatchResult type) so it
 * has zero dependency on that module and can be unit-tested directly with plain object fixtures —
 * anthropic.ts's actual MatchResult satisfies this shape and can be passed in as-is.
 *
 * Order matters: the evidence-downgrade must run before the score computations, so a correction
 * (a 'met' claim with no evidence isn't a confirmed match) actually changes the score, rather than
 * only hiding the symptom after the fact. */
export function applyScoringOverrides<T extends ScorableResult>(result: T): T {
  for (const r of result.requirements) {
    if (r.status === 'met' && !r.evidence?.trim()) r.status = 'insufficient_info';
  }
  result.compatibility = computeCompatibility(result.requirements);
  result.categoryScores = computeCategoryScores(result.requirements, result.categoryScores);
  Object.assign(result, computeRequirementCounts(result.requirements));
  result.criticalGapsCount = computeCriticalGapsCount(result.requirements);
  // Defensive clamp: a malformed AI response must never show realCompatibility < compatibility.
  result.realCompatibility = Math.max(result.realCompatibility, result.compatibility);
  return result;
}
